// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBwdQs-sepNw8uagVNcrG0JRCRHeDBgnE',
    appId: '1:163334285228:web:fa2ccb2cb610af7a187c09',
    messagingSenderId: '163334285228',
    projectId: 'bhl-obe',
    authDomain: 'bhl-obe.firebaseapp.com',
    storageBucket: 'bhl-obe.firebasestorage.app',
    measurementId: 'G-ZXHHCWT436',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtI3ur1xy4oW0eGbstzS2K6PzeJUpsEU',
    appId: '1:163334285228:android:9b3a1f35badd86a9187c09',
    messagingSenderId: '163334285228',
    projectId: 'bhl-obe',
    storageBucket: 'bhl-obe.firebasestorage.app',
  );
}
